[site]
title = "Nathan Gill"
author = "Nathan Gill <nathan.j.gill@outlook.com>"
description = "Nathan Gill's personal website"
base_url = "https://nathanjgill.uk/"
default_template = "page.html"

[build]
include_drafts = false
static_prefix = ""
plugin_dir = "plugins"

[serve]
host = "0.0.0.0"
port = 8080

[[plugin]]
name = "rss_generator.py"
hook = "post"
hash = "d67ad9a57b5c198d22e1e26aa60171a5acfb5c2477a7aeac383320560de8cb48"
